# Docs for the Azure Web Apps Deploy action: https://go.microsoft.com/fwlink/?linkid=2134798
# More GitHub Actions for Azure: https://go.microsoft.com/fwlink/?linkid=2135048

name: Azure App Service - angular-app-tourism(Production), Build and deploy NodeJS app

on:
  push:
    branches:
      - master

env:
  AZURE_WEBAPP_NAME: angular-app-tourism    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './dist/your-app-name'      # set this to the path to your web app project
  NODE_VERSION: '12.x'                # set this to the node version to use


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master


    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present

    - name: Run Azure webapp deploy action using publish profile credentials
      uses: azure/webapps-deploy@v2
      with:
        app-name: angular-app-tourism
        slot-name: Production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_8F997102444249A78B40A156C4FA3ECC }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

